### ISSUE TITLE
Report on Job Architecture & Position Clean Up

### ISSUE THREAD

**Issue by lortrent** [lortrent/projects#119]
#Privacy of Information and Protection:
**Your opinion is your personal information. Please do not include any information which identifies you or others in your response.**

#Description:

Report on state and activities of job architecture and position clean-up and the plan. Decide on what artifacts. This needs to keep employee migration in mind as well.

#Outcome:
- [x]  Initial creation of current position and job classification and accompanying job descriptions.
- [x]  No Need for requirements traceability of changes, why for new data mappings and where the change needs to occur, the old data and new data mapping.  Not required yet.
- [x]  Org Publisher will no loner be used.  Instead EC org chart will be used directly.

**Comment by lagaultier** [comment]
Plan to report at Sprint Review as changes are ongoing
