### ISSUE TITLE
Investigate EC-HCM Data Mapping

### ISSUE THREAD

**Issue by lortrent** [lortrent/projects#120]
#Privacy of Information and Protection:
**Your opinion is your personal information. Please do not include any information which identifies you or others in your response.**

#Description:

Review existing EC -Payroll data mapping as well as what Infotypes we use in HCM and how this will map to EC to address the job architecture clean-up.
Give SE!16 Access.

#Outcome:
- [ ]  Maps the data and highlights issues for any customization in HCM.
- [ ] Informs planning and decisions around job architecture clean-up

#To Complete this ticket:
- [ ]  Complete Tables to map HCM InfoTypes.
- [ ]  Finish identifying EC to HCM mappings.
- [ ]

**Comment by lortrent** [comment]
@RomC2022 Question: Can you pull out a list of recurring payment types or recurring compensation types?  I know about boot allowances but I am wondering about some other ones.

**Comment by RomC2022** [comment]
Hi Lorna,
Here is a list of recurring payments.
Best Rgds,
Rom
