### ISSUE TITLE
Investigate Integration

### ISSUE THREAD

**Issue by lortrent** [lortrent/projects#121]
#Privacy of Information and Protection:
**Your opinion is your personal information. Please do not include any information which identifies you or others in your response.**

#Description:
Investigate AD integration, switching from employee name to employee ID for automation.

#Outcome:
- [ ]  What is  involved, issues, considerations, timing., pre-work tasks
- [ ]   SAP resources  in the project folder
- [ ]  one pager of upcoming tasks  and overview

#To Complete this ticket:
- [ ]  
- [ ] 
- [ ]

**Comment by lortrent** [comment]
Started but nothing to demonstrate or May 6th sprint review.

**Comment by lortrent** [comment]
@amoore-github Hi,  Can you add any documentation you found to SharePoint please. 05Work\Integration

**Comment by amoore-github** [comment]
@lortrent  Hi, the following documents have been added to 05Work\Integration.

SF_ERP_EC_Data_Migration.pdf
SF_ERP_EC_CoreHybrid_Interface.pdf
SF_EC_ERP_UI_Integration.pdf
Links_to_integration_docs.docx (contains links to multiple documents).

**Comment by lortrent** [comment]
@amoore-github Thx.
