### ISSUE TITLE
Update project Stakeholders list

### ISSUE THREAD

**Issue by lortrent** [lortrent/projects#128]
#Privacy of Information and Protection:
**Your opinion is your personal information. Please do not include any information which identifies you or others in your response.**

#Description:
Find and engage a facilities person to participate in identifying provisioning requirements for onboarding, transferring or any movement of employees that requires provisioning of assets.

#Outcome:
- [ ]  Find and secure a person to participate as required.
- [ ]  Update the stakeholders in the project plan.

**Comment by lagaultier** [comment]
Need to identify additional departmental stakeholders that will be required as outlined in Section 3 of the IBC to act as super users, support testing, and support the project through change management

**Comment by lortrent** [comment]
@lagaultier  will you be able to wrap this up this sprint?

@lagaultier Yes.  I just thought you were not at stand up tomorrow.  My mistake.  Thx.
