### ISSUE TITLE
Update Project Stakeholders List

### ISSUE THREAD

**Issue by lagaultier** [lortrent/projects#131]

**Comment by lagaultier** [comment]
Should this be updated prior to charter sign-off?  If not, we can move to later sprint

**Comment by lortrent** [comment]
@lagaultier Hi, Im going to close this ticket as we have ticket #128.  I dont think we need to worry about getting it done before we sign off the charter so it could wait until next sprint.  I will add update the stakeholders list as part of ticket #128
