### ISSUE TITLE
Create an HR Glossary of Terms to Support Employee Journey

### ISSUE THREAD

**Issue by lortrent** [lortrent/projects#173]
#Privacy of Information and Protection:
**Your opinion is your personal information. Please do not include any information which identifies you or others in your response.**

#Description:
Create a document that defines all relevant terms.

#Outcome:
- [ ]  Word. Doc.
- [ ] 
- [ ] 

#To Complete this ticket:
- [ ]  
- [ ] 
- [ ]

**Comment by lortrent** [comment]
@dcaird or @lagaultier , DO you know where @amaunders put the word doc?
I don't see it in the project folder.  Do either of you know where it is and out in the Work folder for now?  Thx.

**Comment by lagaultier** [comment]
@lortrent it is on @amaunders desktop, is it okay to wait until Monday for access?
@lagaultier ok.  sure.
