### ISSUE TITLE
Identify Generic Auxiliary Positions in Job Architecture Spreadsheet

### ISSUE THREAD

**Issue by lortrent** [lortrent/projects#177]
#Privacy of Information and Protection:
**Your opinion is your personal information. Please do not include any information which identifies you or others in your response.**

#Description:
- Discuss with team to determine what columns would be helpful in the spreadsheet.
- In the spreadsheet identify all positions which are used a a generic position such as Recreation Worker, Aquatic Worker.
- Identify which real positions are associated with each generic position. 
#Outcome:
- [ ]  
- [ ] 
- [ ] 

#To Complete this ticket:
- [ ]  
- [ ] 
- [ ]

**Comment by lagaultier** [comment]
Highlighted generic positions in yellow @amaunders to try and link remaining JDs
