### ISSUE TITLE
Update Job Architecture Spreadsheet with Job Descriptions

### ISSUE THREAD

**Issue by lortrent** [lortrent/projects#180]
#Privacy of Information and Protection:
**Your opinion is your personal information. Please do not include any information which identifies you or others in your response.**

#Description:
Collect JD's and updates spreadsheet.  All JD's should be accounted for on the spreadsheet.
Live links to JD's in the spreadsheet.

#Outcome:
- [ ]  
- [ ] 
- [ ] 

#To Complete this ticket:
- [ ]  
- [ ] 
- [ ]

**Comment by lortrent** [comment]
@lagaultier has this been started yet?  If so, can you please put it in progress please.  Also, if you have any blockers please report on the HR Teams channel for sprint stand up tomorrow.  Thx.

**Comment by lagaultier** [comment]
All Regular Union JDs have been linked that have a JD - next steps to distribute to HR Managers/Advisors to link to Aux and Exempt JDs
