### ISSUE TITLE
Identify Technical Requirements

### ISSUE THREAD

**Issue by lortrent** [lortrent/projects#196]
#Privacy of Information and Protection:
**Your opinion is your personal information. Please do not include any information which identifies you or others in your response.**

#Description:
Review the scope to identify and define system integrations that have not been explored.
Review scope for architecture decisions, concerns and follow-up tasks.

-Includes ID Card, elimination of external Org chart, what data must be mastered in ECC and EC, review of @RomC2022  spreadsheet.

#Outcome:
- [x]  reviewed Badge Id system with Darren.  The current Infotypes used in HCM do not exist in SF so we will need to create the these additional attributes using MDF.  Not sure if we will need a UI for the end users to see them? 
- [x]  preliminary review of PA 20 and what will remain in ECC for Payroll.  Looks like it will only be additional payments but each wage type that is used will have to be reviewed with payroll before we can confirm.
- [x] No known additional systems.

#To Complete this ticket:
- [ ]  
- [ ] 
- [ ]

**Comment by mrdarrenmartin** [comment]
Please provide a link to the documents.
