### ISSUE TITLE
Create a Complete List of In Scope Epics, Themes and Transactions

### ISSUE THREAD

**Issue by lortrent** [lortrent/projects#197]
#Privacy of Information and Protection:
**Your opinion is your personal information. Please do not include any information which identifies you or others in your response.**

#Description:
List all HRIS themes, epics and transactions to begin the detailed requirements process.

#Outcome:
- [x]  Created an HRIS Journey List that contains the in-scope product themes and epics.
- [x]  /99Business Process Analysis/HRIS-Journey-List(WIP)
- [ ] 

#To Complete this ticket:
- [ ]  
- [ ] 
- [ ]

**Comment by mrdarrenmartin** [comment]
Please explain why you need to know all the HR transactions in SAP ECC?
