### ISSUE TITLE
Complete the Recruitment PTO Training

### ISSUE THREAD

**Issue by lortrent** [lortrent/projects#259]
#Privacy of Information and Protection:
**Your opinion is your personal information. Please do not include any information which identifies you or others in your response.**

#Description:
99 SF Documentation\Course Material\Training Material Overview & Links to find info for specific course.

#Outcome:
- [ ]  

#Outcome:
- [ ]  
- [ ] 
- [ ] 

#To Complete this ticket:
- [ ]  
- [ ] 
- [ ]

**Comment by lortrent** [comment]
@camyotte -Complete

**Comment by cegede** [comment]
@cegede - Complete

**Comment by lortrent** [comment]
@lortrent Completed

**Comment by lortrent** [comment]
@amaunders -Complete

**Comment by amoore-github** [comment]
@amoore-github - complete
