### ISSUE TITLE
Create a Report Mock-Up for Term and New Hires

### ISSUE THREAD

**Issue by lortrent** [lortrent/projects#276]
#Privacy of Information and Protection:
**Your opinion is your personal information. Please do not include any information which identifies you or others in your response.**

#Description:
A report to show term and new hires has been requested by Payroll. This ticket is create a mockup of the report.  Layout, columns and filter criteria, sorting, totals.  

#Outcome:
- [x]  99 Business Process Analysis/Report Requirements-Payroll.
- [ ] 

#To Complete this ticket:
- [ ]  
- [ ] 
- [ ]

**Comment by camyotte** [comment]
@lortrent : located in Business Process Analysis
