### ISSUE TITLE
Technical Solution For Updating Dual Employee and Dual Central Person

### ISSUE THREAD

**Issue by lortrent** [lortrent/projects#376]
#Privacy of Information and Protection:
**Your opinion is your personal information. Please do not include any information which identifies you or others in your response.**

#Description:
One person has two employee ids each employee id points to a unique Central Person.
Combine into one CP with two employee ids without impacting history or payroll. 

what are the steps?
Can we also try this in QA?

#Outcome:
- [x]  99JobArchitecture Clean-Up/Central Person Correction.docx
- [ ] 
- [ ] 

#To Complete this ticket:
- [ ]  Update records in QA so Corinne can check if there's impact to Payroll
- [ ] 
- [ ]

**Comment by ivydavid** [comment]
CP has relationship 209 to P object but cannot create relationship if P is already withdrawn.

Check with Lorna:
1) Data Migration - will this include inactive EEs?
2) Get EE list with multiple CPs
