### ISSUE TITLE
Provide Examples of the Supervisor Adjustment Job

### ISSUE THREAD

**Issue by lortrent** [lortrent/projects#441]
#Privacy of Information and Protection:
**Your opinion is your personal information. Please do not include any information which identifies you or others in your response.**

#Description:

Need to understand the pros and cons of using this job to automatically update the supervisor field on a daily basis to ensure that all employees have a supervisor.  Impacts replication to ECC

Situation where the job will cause an issue: 
- Terminate a Manager in EC
- On Termination Transfer Direct Reports to a new Manager who is not a part of the Position Hierarchy.
- Direct Reports now have new manger outside of Position Hierarchy
- The Automated Daily Hierarchy Adaptation job runs and changes to Manger to the next incumbent in the Position hierarchy.

#Outcome:
- Currently you cannot provide any exceptions to this processing job.
- If this job is scheduled to run then it will adapt all Hierarchy.
- If you wish for the Position Hierarchy and the Reporting Hierarchy to be different then, we do not recommend using this job.
Decision: DO not use this.

#To Complete this ticket:
- Decision to use the job.  We typically recommend not to enable this and most clients do want this automated at this level.

**Comment by ctimlick** [comment]
Situation:
- Terminate a Manager in EC
- On Termination Transfer Direct Reports to a new Manager who is not a part of the Position Hierarchy.
- Direct Reports now have new manger outside of Position Hierarchy
- The Automated Daily Hierarchy Adaptation job runs and changes to Manger to the next incumbent in the Position hierarchy.

Impact:
- Currently you cannot provide any exceptions to this processing job.
- If this job is scheduled to run then it will adapt all Hierarchy.
- If you wish for the Position Hierarchy and the Reporting Hierarchy to be different then, we do not recommend using this job.
