### ISSUE TITLE
Prepare Draft Entry and Exit Data Migration Score Cards

### ISSUE THREAD

**Issue by lortrent** [lortrent/projects#449]
#Privacy of Information and Protection:
**Your opinion is your personal information. Please do not include any information which identifies you or others in your response.**

#Description:
Prepare sample entry and exit score card criteria for CRD to review.

#Outcome:
- [x]  Upload in SAP JAM
- [ ] 
- [ ] 

#To Complete this ticket:
- Review and adjust based on CRD feedback
- [ ] 
- [ ]

**Comment by ctimlick** [comment]
Required for IT2
