### ISSUE TITLE
Screening question Score - Does it Disqualify the Candidate

### ISSUE THREAD

**Issue by lortrent** [lortrent/projects#462]
#Privacy of Information and Protection:
**Your opinion is your personal information. Please do not include any information which identifies you or others in your response.**

#Description:

#Outcome:
- [x]  No.  To automatically disqualify a candidate questions must be marked as Disqualifiers.
- [ ] 
- [ ] 

#To Complete this ticket:
- [ ]  
- [ ] 
- [ ]

**Comment by patrickmpuanga** [comment]
Hi Lorna, 

 Scores on the screening question does not disqualify candidates. The screening question asked to the candidate must be marked as a disqualifier for the candidate to be automatically moved. If the screening questions are not marked as disqualifiers but there is a score total placed on all questions, this will simply be used to compare from candidate to candidate, not to disqualify automatically.
