### ISSUE TITLE
Determine if Delegate Workflows will work with Job Requisition Route Maps

### ISSUE THREAD

**Issue by lortrent** [lortrent/projects#463]
#Privacy of Information and Protection:
**Your opinion is your personal information. Please do not include any information which identifies you or others in your response.**

#Description:

Delegate to a person who is in the recruitment group/team
Proxy to that person
See the delegation.
Does the workflow show up on the home page/to do list as an approval.
Can the delegate approve it?
Doe sit move on to the next step successfully?
What does the audit show?  Does it show that the delegate did the approval?

#Outcome:
- [ ]  
- [ ] 
- [ ] 

#To Complete this ticket:
- [x]  Need data in the system to validate.
- [ ] 
- [ ]

**Comment by patrickmpuanga** [comment]
Please note that recruiting does not support the delegate function. The requisition or offer approval will have to be reassigned using the 'Reassign Job Requisition' or 'Reassign Offer Approval' function. 

Please see the below KBA for reference

KBA 3287471:
https://userapps.support.sap.com/sap/support/knowledge/en/3287471
