### ISSUE TITLE
Provide Guide to Enable 0302 Additional Actions in ECC

### ISSUE THREAD

**Issue by lortrent** [lortrent/projects#472]
#Privacy of Information and Protection:
**Your opinion is your personal information. Please do not include any information which identifies you or others in your response.**

#Description:
Provide the guide so we can set this up in ECC.

#Outcome:
- [x] Document attached
- [ ] 
- [ ] 

#To Complete this ticket:
- [x] Document attached outlining setting up IT0302 (additional actions) and the action / action reason for No Shows  
- [ ] 
- [ ]

**Comment by ctimlick** [comment]
[https://app.zenhub.com/files/468877700/c2e39af6-bfea-41da-9706-1331a53da1ab/download](https://app.zenhub.com/files/468877700/c2e39af6-bfea-41da-9706-1331a53da1ab/download)
