### ISSUE TITLE
How Many Characters for the Skills Name in SF

### ISSUE THREAD

**Issue by lortrent** [lortrent/projects#480]
#Privacy of Information and Protection:
**Your opinion is your personal information. Please do not include any information which identifies you or others in your response.**

#Description:
Any drop lists for selection.

#Outcome:
- Skills can be 256 characters 
- Job Role and Profile are 128 characters 
- See attachment for how skills appear
- [x]  FINAL OUTCOME: The Skills library will not be implemented and he Key Skills & Abilities section will remain text in the job profile.  Added to the roadmap to revisit.

#To Complete this ticket:
- [ ] Colleen, could you please provide screenshots of how the skill title appears on a job posting or job description? 
- [ ] 
- [ ] Image below shows that long skill names do render properly in the job profile, so ok to proceed.

![image](https://user-images.githubusercontent.com/103147133/220753019-39460b47-a8c9-4bab-9b5f-d3bc9329a387.png)

**Comment by ctimlick** [comment]
![CRD Skills adding to Role.jpg](https://images.zenhubusercontent.com/63dadd0416b93246f81257df/cbe73962-491e-45e2-9839-89123530d32c)![CRD view skills on role.jpg](https://images.zenhubusercontent.com/63dadd0416b93246f81257df/d5c765ac-48bf-4d66-b574-011d99042eae)
