### ISSUE TITLE
Provide Deep Link to Org Chart

### ISSUE THREAD

**Issue by lortrent** [lortrent/projects#498]
#Privacy of Information and Protection:
**Your opinion is your personal information. Please do not include any information which identifies you or others in your response.**

#Description:
People's org chart

#Outcome:
- [x]  test this in IT1
- [x]  Position Org Chart only.  Start at the top. CAO
- [ ] 

#To Complete this ticket:
- [ ]  
- [ ] 
- [ ]

**Comment by ctimlick** [comment]
Will provide the link once configuration of EC is completed for IT1
