### ISSUE TITLE
Review the RICEFW  Enhancements Code

### ISSUE THREAD

**Issue by lortrent** [lortrent/projects#507]
#Privacy of Information and Protection:
**Your opinion is your personal information. Please do not include any information which identifies you or others in your response.**

#Description:
Review and determine impacts of HR enhancements.

#Outcome:
- [ ]  
- [ ] 
- [ ] 

#To Complete this ticket:
- [ ]  
- [ ] 
- [ ]

**Comment by nabilferrani** [comment]
Just sent screenshots of error message & SU53 to CRD's technical team as I'm not able to review code in CMOD

**Comment by lortrent** [comment]
@nabilferrani   Can we close this ticket now?  is it done?
