### ISSUE TITLE
Set Up Entitlements - Schedule a Work Session

### ISSUE THREAD

**Issue by lortrent** [lortrent/projects#508]
#Privacy of Information and Protection:
**Your opinion is your personal information. Please do not include any information which identifies you or others in your response.**

#Description:
Review with Rizing and set up entitlements.
Senthil to book a meeting with Rizing.

#Outcome:
- [ ]  
- [ ] 
- [ ] 

#To Complete this ticket:
- [ ]  
- [ ] 
- [ ]

**Comment by arnabmaji-rizing** [comment]
Entitlements added to the Existing subaccount. Further discussion is planned for determining the Cloud Integrations landscape.

**Comment by nabilferrani** [comment]
Communication has been sent to CRD's technical team to confirm availability for a working session to complete any required work in Cloud Foundry subaccount

**Comment by nabilferrani** [comment]
Dev subaccount has been created in Cloud Foundry, entitlements configured...and integration suite should now be enabled. CRD's Technical Team to confirm as we ended the working session right after we've launched last step to enable integration suite.
