### ISSUE TITLE
Test Basic Pay Replication to Ensure ECC Indirect Valuation Has No Impact on Replication

### ISSUE THREAD

**Issue by lortrent** [lortrent/projects#529]
#Privacy of Information and Protection:
**Your opinion is your personal information. Please do not include any information which identifies you or others in your response.**

#Description:
How does this impact replication?

#Outcome:
- [x]  discussion
- [ ]  @ctimlick has indicated that SF uses direct valuation but should not be an issue for replication. But we will need to test in the sandbox.
- [x]   Turn off indirect valuation -turn on replication job

#To Complete this ticket:
- [ ]  
- [ ] 
- [ ]

**Comment by ctimlick** [comment]
Replication will use direct valuation for all replicated IT0008 records (the actual rate/amount are passed from EC).  Discuss what needs to be done in ECC to accomodate
