### ISSUE TITLE
Provide RCM Notification Extract

### ISSUE THREAD

**Issue by lortrent** [lortrent/projects#531]
#Privacy of Information and Protection:
**Your opinion is your personal information. Please do not include any information which identifies you or others in your response.**

#Description:
Provide a extract of all RCM notification with message text where available and custom messages for CRD to update and complete.

#Outcome:
- [ ]  Spreadsheet on JAM
- [ ] 
- [ ] 

#To Complete this ticket:
- [ ]  
- [ ] 
- [ ]

**Comment by patrickmpuanga** [comment]
Hi Lorna, 

 I have uploaded the RCM Email templates to the JAM site. They can be found in the Recruiting Management>Workbooks>Iteration 1 folder
