### ISSUE TITLE
Test AD Integration with New User Creation and Employee Movement

### ISSUE THREAD

**Issue by lortrent** [lortrent/projects#599]
#Privacy of Information and Protection:
**Your opinion is your personal information. Please do not include any information which identifies you or others in your response.**

#Description:
Test to see if it works and determine the internal workflow for provisioning a user.
Both onboard, move and offboard.
Includes Phone #s from AD to SF.

#Outcome:
- [ ]  New hires that are future dated work.
- [ ]  New hires that have been converted to employees - work
- [ ] 

#To Complete this ticket:
- [ ]  
- [ ] 
- [ ]

**Comment by nabilferrani** [comment]
Working session is required to test all scenarios including the write back, this should be scheduled during IT2 testing as we need new hire data...
