### ISSUE TITLE
Correct Hire Date for 6 Employees in PROD

### ISSUE THREAD

**Issue by lortrent** [lortrent/projects#605]
#Privacy of Information and Protection:
**Your opinion is your personal information. Please do not include any information which identifies you or others in your response.**

#Description:

Add a hire date for these 6 employees.  @ivydavid to provide list.

#Outcome:
- [ ]  
- [ ] 
- [ ] 

#To Complete this ticket:
- [ ]  
- [ ] 
- [ ]

**Comment by camyotte** [comment]
This is completed
