### ISSUE TITLE
Take EC Project Orientation Training.

### ISSUE THREAD

**Issue by lortrent** [lortrent/projects#89]
#Privacy of Information and Protection:
**Your opinion is your personal information. Please do not include any information which identifies you or others in your response.**

#Description:
Take online training to become familiar with EC.

https://saplearninghub.plateau.com/learning/user/catalogsearch/catalogSearchDispatchAction.do?searchType=filteredSearch&keywords=EC%20PTO

#Outcome:
- [ ]  
- [ ] 
- [ ] 

#To Complete this ticket:
- [ ]  
- [ ] 
- [ ]

**Comment by camyotte** [comment]
Can you link the course please.
@camyotte - done.  Thx.

**Comment by lagaultier** [comment]
LG - Complete

**Comment by RomC2022** [comment]
RC - Complete

**Comment by amaunders** [comment]
AM - Complete

**Comment by dcairdcon** [comment]
I have yet to be able to log in to SAP despite repeated password resets.  I have asked JH if she can help.

**Comment by amoore-github** [comment]
AM - Complete

**Comment by dcairdcon** [comment]
DONE!  DC

**Comment by camyotte** [comment]
CA-done
